apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-backend
  template:
    metadata:
      labels:
        app: employee-backend
    spec:
      containers:
      - name: employee-backend
        image: <your_dockerhub_username>/employee-backend:v1
        ports:
        - containerPort: 5000
